### PR TITLE
fix: remove invalid characters in output.tf

### PR DESCRIPTION
**Pull request by YunYangHenryLee**
image_2023_05_11T08_01_41_832Z

Fixed output.tf by removing invalid characters 

#  [Remove all cloudbuild CD related settings](https://github.com/GoogleCloudPlatform/terraform-large-data-sharing-java-webapp/pull/6)

Since we only deploy the entire application with terraform apply, we do not need cloudbuild for continuous deployment anymore. Related cloudbuild configurations have been removed.

The removal of the related files  is related to the following PR: https://github.com/GoogleCloudPlatform/terraform-large-data-sharing-java-webapp/pull/6

### CODE REVIEW

**Comment by bourgeoisor** [comment]
This PR seems to remove a handful of files-- Is that intentional?

**Comment by YunYangHenryLee** [comment]
> This PR seems to remove a handful of files-- Is that intentional?

Yes, that's intentional. 
Currently,  cloudbuild yamls and its related scripts are only used for internal testing and are not provided to users. 

The removal of the related files  is related to the following PR: https://github.com/GoogleCloudPlatform/terraform-large-data-sharing-golang-webapp/pull/6.

This PR is dependent on "Add api dependency #6", could you first merge #6 so that there won't be a merge conflict. Thanks

**Review by telpirion — APPROVED** [review]

**Pull request merged**
